### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE] in Mk2_out Flow

### ISSUE THREAD

**Issue by rankerson** [liaan/victron_thethingbox#3]
Hello,

I just updated my node-red to version v0.19.5 and since then I unfortunately have an issue with the otherwise perfect flow. Installing the last version of the serial node to v0.8.8 did not help neither.

I receive the following error message from the node Mk2_out:
"TypeError [ERR_INVALID_ARG_TYPE]: The "list[1]" argument must be one of type Array, Buffer, or Uint8Array. Received type string" - checking the "Make command" flow I see that a buffer is created and also a debug output shows me a buffer in msg.payload. I do not know, how I can solve that. Would you be able to help me?

Thanks in advance
Ranki

**Comment by rankerson** [comment]
Hello together,

after more research I found the issue now. It is not caused in this flow, but in an update of node-red/the serial node. Here is, how you can solve it, if you have the same issue:
In the settings of the connected serial port: "Add character to output messages" get a value of "false" in it. This value caused the problem. Remove the value and leave it blank solved the it.
I found this solution on: https://discourse.nodered.org/t/send-buffer-over-usb-serial-node/16494/4

Cheers
Ranki

**Comment by liaan** [comment]
Glad you got sorted ... I completely missed the alerts for new bugs
